
#' Build Tab 2
#'
#' @param alldata a list of proposal, contact, qualification, and role data built by get_tab2_data().
#' @param proposal_data a data frame of proposal data, as generated by get_proposal_data (or the proposal section of get_tab2_data()). Only use this if you do not specify anything for alldata.
#' @param contact_data  a data frame of contact report data, as generated by get_contact_reports (or the contact section get_tab2_data()). Only use this if you do not specify anything for alldata.
#' @param role_data  a data frame of role data, as generated by get_roles (or the role section get_tab2_data()). Only use this if you do not specify anything for alldata.
#' @param start_fy what fiscal year should the bar charts start at
#'
#' @return a list with 8 elements, one for each of the metrics on Tab 2
#' @export
#'
build_tab2  <- function(
      alldata
    , proposal_data
    , contact_data
    , qual_data
    , role_data
    , start_fy = 2015
  ) {

  # need to collect data by default -----------------------------------------


  if(!missing(alldata)) {

    proposal_data = alldata$proposal_data
    contact_data  = alldata$contact_data
    qual_data     = alldata$qual_data
    role_data     = alldata$role_data

  }




  proposal_data  <- proposal_data |>
    collect()
  contact_data  <- contact_data |>
    collect()
  qual_data  <- qual_data |>
    collect()
  role_data  <- role_data |>
    collect()

  # build trends ------------------------------------------------------------


  visits         <- build_contact_trends(contact_data = contact_data, role_data = role_data, type = 'visits', first_fy = start_fy)
  unique_visits  <- build_contact_trends(contact_data = contact_data, role_data = role_data, type = 'unique visits', first_fy = start_fy)
  sig_contacts   <- build_contact_trends(contact_data = contact_data, role_data = role_data, type = 'significant contacts', first_fy = start_fy)

  qualifications  <- build_qualifications_trend(qual_data = qual_data, first_fy = start_fy)

  ask_n     <- build_ask_commit_trends(proposal_data = proposal_data, metric ='asks'   , value = '#', first_fy = start_fy)
  ask_g     <- build_ask_commit_trends(proposal_data = proposal_data, metric ='asks'   , value = '$', first_fy = start_fy)
  commit_n  <- build_ask_commit_trends(proposal_data = proposal_data, metric ='commits', value = '#', first_fy = start_fy)
  commit_g  <- build_ask_commit_trends(proposal_data = proposal_data, metric ='commits', value = '$', first_fy = start_fy)

  list(
      visits         = visits
    , unique_v       = unique_visits
    , sig_contacts   = sig_contacts
    , qualifications = qualifications
    , asks_n         = ask_n
    , asks_total     = ask_g
    , commits_n      = commit_n
    , commits_total  = commit_g
  )

}
