
#' Build Tab 2
#'
#' @param proposal_data a data frame of proposal data, as generated by get_proposal_data (or get_tab2_data())
#' @param contact_data  a data frame of contact report data, as generated by get_contact_reports (or get_tab2_data())
#' @param role_data  a data frame of role data, as generated by get_roles (or get_tab2_data())
#' @param start_fy what fiscal year should the bar charts start at
#'
#' @return a list with 8 elements, one for each of the metrics on Tab 2 (qualifications isn't done yet)
#' @export
#'
build_tab2  <- function(
      proposal_data = get_tab2_data()['proposal_data']
    , contact_data  = get_tab2_data()['contact_data']
    , role_data     = get_tab2_data()['role_data']
    , start_fy = 2015
  ) {


  # build trends ------------------------------------------------------------


  visits         <- build_contact_trends(contact_data = contact_data, role_data = role_data, type = 'visits', first_fy = start_fy)
  unique_visits  <- build_contact_trends(contact_data = contact_data, role_data = role_data, type = 'unqiue visits', first_fy = start_fy)
  sig_contacts   <- build_contact_trends(contact_data = contact_data, role_data = role_data, type = 'significant contacts', first_fy = start_fy)


  # NEED QUALIFICATIONS!!!!!!!!!!!!!

  ask_n     <- build_ask_commit_trends(proposal_data = proposal_data, metric ='asks'   , value = '#', first_fy = start_fy)
  ask_g     <- build_ask_commit_trends(proposal_data = proposal_data, metric ='asks'   , value = '$', first_fy = start_fy)
  commit_n  <- build_ask_commit_trends(proposal_data = proposal_data, metric ='commits', value = '#', first_fy = start_fy)
  commit_g  <- build_ask_commit_trends(proposal_data = proposal_data, metric ='commits', value = '$', first_fy = start_fy)

  list(
    visits = visits
    , unique_v = unique_visits
    , sig_contacts = sig_contacts
    # , qualifications = qualifications
    , asks_n = ask_n
    , asks_total = ask_g
    , commits_n = commit_n
    , commits_total = commit_g
  )

}
